import Head from "next/head";
import Link from "next/link";
import Navbar from "~/components/Navbar";
import Cover from "~/components/Cover";
import Hero from "~/components/Hero";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="relative h-screen bg-[var(--bg-color)] overflow-x-hidden overflow-y-scroll">
        <Cover/>
        <Navbar/>
        <Hero/>
      </main>
    </>
  );
}
