import Head from "next/head";
import Navbar from "~/components/Navbar";
import Cover from "~/components/Cover";
import Hero from "~/components/Hero";
import { useMotionValueEvent, useScroll } from "framer-motion";
import { useCallback, useRef } from "react";
import { useScrollStore } from "~/store";

export default function Home() {
  const ref = useRef<HTMLDivElement>(null);
  const { scrollYProgress } = useScroll({
    container: ref,
  });
  const { setScroll } = useScrollStore();

  useMotionValueEvent(scrollYProgress, "change", (latest) => {
    setScroll(latest);
  });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="relative h-screen overflow-x-hidden bg-[var(--bg-color)]" ref={ref}>
        <Cover />
        <Navbar />
        <Hero />
      </main>
    </>
  );
}
